Added connection info as a second parameter
ibraheemdev/astra pull request #3
Opened 2023-02-13 05:42 UTC by fatfingers23

This is to resolve #2 .  I implemented it as best as possible, following the issue's details. There is now a second parameter that passes along with the request. It is connection_info, which holds info I got from the TcpSocket connection, like the request IP. I am still learning Rust, so please let me know if there is something I need to do differently. I was wondering if I should be unwrapping the local_addr or peer_addr like I am. Also, with the way I passed the new struct connection info from the reactor.

2023-02-24 03:03 UTC, ibraheemdev requested changes
Looks good overall, just a couple notes.

2023-02-24 03:03 UTC, ibraheemdev commented on src/net.rs
> +        let local_addr = sys.local_addr().unwrap();
I don't really see the point of astra exposing the `local_addr`.

2023-02-24 03:03 UTC, ibraheemdev commented on src/net.rs
> +        let connection_info = ConnectionInfo {
I don't think we need to store this on the `TcpStream`. We can just get it in the server loop.

2023-02-24 03:03 UTC, ibraheemdev commented on src/net.rs
> +        let peer_addr = sys.peer_addr().unwrap();
Regarding unwrapping, I would prefer to expose it as an `Option<SocketAddr>`.

2023-02-24 08:16 UTC, fatfingers23 commented
Thank you for the feedback! I've made the changes you asked for. Please let me know if I missed anything or if something needs to be changed.

2023-03-27 23:11 UTC, ibraheemdev commented
This looks great. Thanks! I'll try to get a release out soon.

2023-03-27 23:11 UTC, merged